# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with healthcheck
  healthcheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/healthcheck.healthcheckRoute
      Runtime: nodejs18.x
      # MemorySize: 128
      # Timeout: 100
      Description: A Lambda function to check health of recruitment portal
      # Policies:
      #   # Give Lambda basic execution Permission to the function
      #   - AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::XXXXXXXXXXXXX:role/lambda-role-recruitment-portal-v1 #Role with LambdaBasicExecutionRole Policy
      Events:
        HealthCheckAPI:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: get
  # This is a Lambda function config associated with authentication
  authFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/auth.authRoutes
      Runtime: nodejs18.x
      # MemorySize: 128
      # Timeout: 100
      Description: A Lambda function to authenticate in recruitment portal
      # Policies:
      #   # Give Lambda basic execution Permission to the function
      #   - AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::XXXXXXXXXXXXXX:role/lambda-role-recruitment-portal-v1 #Role with LambdaBasicExecutionRole Policy
      Events:
        SignUpAPI:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: post
        SignInAPI:
          Type: Api
          Properties:
            Path: /auth/signin
            Method: post
        GetSessionAPI:
          Type: Api
          Properties:
            Path: /auth/session
            Method: get
        SignoutAPI:
          Type: Api
          Properties:
            Path: /auth/signout
            Method: get

Outputs:
  RecruitmentPortalURL:
    Description: "API Base URL for Recruitment portal"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
